# -*- coding: utf-8 -*-
"""Qwen AdaLoRA_finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTQ0vO5BHKnQyz--aeF7QO3_DoZzQqLf
"""

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
from unsloth import FastLanguageModel
import torch
from transformers import TrainingArguments, Trainer
from peft import AdaLoraConfig, get_peft_model
from trl import SFTTrainer
from transformers import TrainingArguments, DataCollatorForLanguageModeling, Trainer
from unsloth import is_bfloat16_supported
from huggingface_hub import login
from google.colab import drive
from huggingface_hub import HfApi, Repository
import os
import os
import json
from datasets import load_dataset
from huggingface_hub import login
import datasets
from datasets import load_dataset
from unsloth import unsloth_train

ds = load_dataset("ToxicityPrompts/PolyGuardMix")
training_data = ds['train']

# Configuration
HF_TOKEN = "your huggingface token"  # Get from https://huggingface.co/settings/tokens
REPO_NAME = "Benjaminpwh/qwen2.5-7b-instruct-poly-adaLORA-6"  # Format: "username/repo"
CHECKPOINT_DIR = "your checkpoint directory"  # Local dir containing your checkpoint files
drive.mount('/content/drive')

#training_data=training_data.select(range(100))

###### Load model ###############
#def formatting_function(examples):
base_model = "Qwen/Qwen2.5-7B-Instruct"
adapter_path = "Benjaminpwh/qwen2.5-7b-instruct-poly-adaLORA-6"

# 1. Load model WITHOUT LoRA/PEFT
base_model, tokenizer = FastLanguageModel.from_pretrained(
    "Benjaminpwh/qwen2.5-7b-instruct-poly-adaLORA-6",
    load_in_4bit=False,
    device_map="auto",
    #torch_dtype=torch.float16,
)

#to load the partially tuned adalora config
adalora_config_loaded = AdaLoraConfig.from_pretrained("Benjaminpwh/qwen2.5-7b-instruct-poly-adaLORA-6")
adalora_config_loaded.inference_mode = False #key fix! Initially, my inference_mode was True, which froze all the parameters and prevented further training
print(adalora_config_loaded)
peft_model = get_peft_model(base_model, adalora_config_loaded)
peft_model.print_trainable_parameters()



adalora_config = AdaLoraConfig(
    task_type="CAUSAL_LM",          # Task type (SEQ_CLS, CAUSAL_LM, etc.)
    init_r=12,                  # Initial rank
    target_r=8,                   # Target rank after pruning
    beta1=0.85,                  # SVD hyperparameter
    beta2=0.85,                  # SVD hyperparameter
    tinit=1000,                   # Warmup steps
    tfinal=15000,                 # Final steps
    deltaT=50,                   # Rank adjustment interval
    lora_alpha=16,               # LoRA scaling factor
    lora_dropout=0.1,           #regularization coefficient
    inference_mode=False,         # Set True for inference
    total_step = 50000
)

peft_model = get_peft_model(model, adalora_config)
peft_model.print_trainable_parameters()

def formatting_function(data_sample):
    prompt = data_sample['prompt']
    response = data_sample['response']
    if not response:
      response = 'None'
    response_harm_label = data_sample['response_harm_label']
    response_safety_categories = data_sample['response_safety_categories']
    prompt_harm_label = data_sample['prompt_harm_label']
    prompt_safety_categories = data_sample['prompt_safety_categories']
    response_refusal_label = data_sample['response_refusal_label']

    instructions = f'''
      <|im_start|>system You are a classifier for analyzing
      interactions between humans and LLMs.
      Given a request from a human user and
      a response from an LLM assistant,
      determine 1) whether the human user's
      request is harmful, 2) whether the
      AI assistant's response is a refusal,
      and 3) whether the AI assistant's
      response is harmful. In addition,
      identify the policies violated if
      the interaction is unsafe and harmful
      according to the safety policy with
      the below categories..

      <BEGIN UNSAFE CONTENT CATEGORIES>
      S1: Violent Crimes.
      S2: Non-Violent Crimes.
      S3: Sex Crimes.
      S4: Child Exploitation.
      S5: Defamation.
      S6: Specialized Advice.
      S7: Privacy.
      S8: Intellectual Property.
      S9: Indiscriminate Weapons.
      S10: Hate.
      S11: Self-Harm.
      S12: Sexual Content.
      S13: Elections.
      S14: Code Interpreter Abuse.
      <END UNSAFE CONTENT CATEGORIES><|im_end|>

      <|im_start|>user {prompt} <|im_end|>

      <|im_start|>assistant {response}<|im_end|>

      <|im_start|>assistant Harmful request: {prompt_harm_label}
      Request safety violations: {prompt_safety_categories}
      Response refusal: {response_refusal_label}
      Harmful response: {response_harm_label}
      Response safety violations: {response_safety_categories}<|im_end|>
      '''

    return {'text': instructions}

###### process data ########

dataset_mapped = training_data.map(formatting_function)

if tokenizer is None:
  print("FATAL ERROR: Tokenizer failed to load. Cannot proceed.")
        # You might want to add a sys.exit() or raise an exception here
        # to stop execution if the tokenizer is essential.
else:
  print("Tokenizer loaded successfully.")

print(dataset_mapped[0])



"""info about chat templates for qwen https://qwen.readthedocs.io/en/latest/getting_started/concepts.html

<|im_start|>system
You are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>
<|im_start|>user
hello<|im_end|>
<|im_start|>assistant
Hello! How can I assist you today? Let me know if you have any questions or need help with something. I'm here to help!<|im_end|>
<|im_start|>user
Explain large language models like I'm 5.<|im_end|>
<|im_start|>assistant
"""

# https://unsloth.ai/blog/gradient 0 fix gradient
torch.cuda.empty_cache()
output_directory = "/content/drive/MyDrive/575J"


## name of your model #
repo_name = f"qwen2.5-7b-instruct-poly-adaLORA-6"

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False  # Important: We're not doing masked LM
)

trainer = SFTTrainer(
    model = peft_model,
    tokenizer = tokenizer,
    train_dataset = dataset_mapped,
    #eval_dataset = val_data,
    dataset_text_field = "text",
    #formatting_func = formatting_func,
    #max_seq_length = max_seq_length,
    data_collator = data_collator,

    args = TrainingArguments(
        output_dir = output_directory,
        per_device_train_batch_size = 8,
        gradient_accumulation_steps = 16 ,
        learning_rate = 2e-4,
        fp16 = False,
        bf16 = True,
        num_train_epochs=1,

        # Checkpointing and validation
        #eval_strategy="no",
        #eval_steps=5,
        save_steps=100,
        save_total_limit=2,
        #load_best_model_at_end=True,
        #metric_for_best_model="eval_loss",
        lr_scheduler_type="cosine",

        # Logging parameters
        logging_dir="./logs",                # Directory for logs
        logging_steps=100,                    # Log every 5 steps
        logging_first_step=True,             # Log the first step

        # Hugging Face Hub parameters
        push_to_hub=True,                    # Push model to Hugging Face Hub
        hub_model_id=repo_name,
        hub_strategy="every_save",           # Push every time we save a checkpoint
        hub_private_repo=False,              # Make the repository public
       

    )
)


# unsloth_train fixes gradient_accumulation_steps
trainer_stats = unsloth_train(trainer, resume_from_checkpoint=True)


print("Starting training...")



trainer.push_to_hub("fine-tuned qwen model")


# --- Push to Hub --- #
def push_checkpoint_to_hub():
    # Initialize HF API
    api = HfApi(token=HF_TOKEN)

    # Create repo if it doesn't exist (optional)
    try:
        api.create_repo(repo_id=REPO_NAME, exist_ok=True)
    except Exception as e:
        print(f"Repo already exists or error: {e}")

    # Upload all files from checkpoint dir
    print("Uploading files...")
    for root, _, files in os.walk(CHECKPOINT_DIR):
        for file in files:
            local_path = os.path.join(root, file)
            hub_path = os.path.relpath(local_path, CHECKPOINT_DIR)
            api.upload_file(
                path_or_fileobj=local_path,
                path_in_repo=hub_path,
                repo_id=REPO_NAME,
            )
    print(f"✅ Checkpoint pushed to: https://huggingface.co/{REPO_NAME}")


push_checkpoint_to_hub()

